### ISSUE TITLE
  Could not find package ankitpokhrel/laravel-pagebuilder at any version for your minimum-stability (dev).

### ISSUE THREAD

**Issue by ariefadjie** [ankitpokhrel/laravel-pagebuilder#2]
Hi, get error when run composer require ankitpokhrel/laravel-pagebuilder
[InvalidArgumentException]
Could not find package ankitpokhrel/laravel-pagebuilder at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by ankitpokhrel** [comment]
I haven't actually started working on the package yet. You can watch the package to get development notifications.
